-- Web chat session persistence for the retailer dashboard assistant.
-- Each row holds a conversation thread scoped to one retailer (tenant_id).
-- session_id is generated by the browser (UUID) and sent with every request.

CREATE TABLE IF NOT EXISTS core.chat_sessions (
    session_id      UUID        PRIMARY KEY,
    tenant_id       UUID        NOT NULL REFERENCES core.tenants(id) ON DELETE CASCADE,
    title           TEXT,
    message_history JSONB       NOT NULL DEFAULT '[]',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_message_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS chat_sessions_tenant_idx
    ON core.chat_sessions(tenant_id, last_message_at DESC);
