"""
Agentic Recommendation Roadmap System.

Every recommendation goes through a managed lifecycle:

  discovery → recommendation_ready → awaiting_approval
  → approved / modified → executing → monitoring
  → reviewing → completed
  (or blocked / expired at any stage)

Claude uses the roadmap tools to give management real-time visibility,
intelligent analysis, and prioritised next-step guidance.
"""
from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from typing import Any
from uuid import UUID

import psycopg
from psycopg.rows import dict_row

logger = logging.getLogger("whatsapp_assistant.roadmap")

# ── Stage metadata ─────────────────────────────────────────────────────────────

STAGE_ORDER = [
    "discovery",
    "recommendation_ready",
    "awaiting_approval",
    "approved",
    "modified",
    "executing",
    "monitoring",
    "reviewing",
    "completed",
]

STAGE_LABELS: dict[str, str] = {
    "discovery":            "🔍 Discovery & Analysis",
    "recommendation_ready": "💡 Recommendation Ready",
    "awaiting_approval":    "⏳ Awaiting Approval",
    "approved":             "✅ Approved",
    "modified":             "✏️ Modified & Pending",
    "executing":            "⚙️ Executing",
    "monitoring":           "📊 Monitoring (7-day)",
    "reviewing":            "📋 Performance Review (14-day)",
    "completed":            "🏁 Completed",
    "blocked":              "🔴 Blocked",
    "expired":              "💀 Expired",
}


# ── Schema migration ───────────────────────────────────────────────────────────

async def ensure_roadmap_tables(db_url: str) -> None:
    """Idempotent migration — creates all roadmap tracking tables."""
    conn = await psycopg.AsyncConnection.connect(db_url)
    try:
        async with conn.cursor() as cur:
            await cur.execute(
                """
                CREATE TABLE IF NOT EXISTS whatsapp.recommendation_roadmaps (
                    id                        BIGSERIAL    PRIMARY KEY,
                    tenant_id                 UUID         NOT NULL REFERENCES core.tenants(id) ON DELETE CASCADE,
                    recommendation_id         UUID         REFERENCES marketing.recommendations(id) ON DELETE SET NULL,
                    sku_id                    TEXT         NOT NULL,
                    product_name              TEXT         NOT NULL,
                    decision_type             TEXT         NOT NULL
                                              CHECK (decision_type IN ('PROMOTE','MARKDOWN','CLEAR','HOLD')),
                    current_stage             TEXT         NOT NULL DEFAULT 'recommendation_ready'
                                              CHECK (current_stage IN (
                                                  'discovery','recommendation_ready','awaiting_approval',
                                                  'approved','modified','executing','monitoring',
                                                  'reviewing','completed','blocked','expired'
                                              )),
                    -- Rich context generated by Claude Haiku
                    context_summary           TEXT,
                    reasoning                 TEXT,
                    expected_impact           TEXT,
                    risks                     TEXT,
                    alternatives              TEXT,
                    next_best_step            TEXT,
                    -- Metrics snapshot at recommendation time
                    confidence_pct            NUMERIC(5,2),
                    suggested_discount_pct    NUMERIC(5,2),
                    -- Lifecycle timestamps
                    created_at                TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
                    approved_at               TIMESTAMPTZ,
                    executed_at               TIMESTAMPTZ,
                    completed_at              TIMESTAMPTZ,
                    last_followup_at          TIMESTAMPTZ,
                    next_followup_at          TIMESTAMPTZ  DEFAULT NOW() + INTERVAL '4 hours',
                    expires_at                TIMESTAMPTZ  DEFAULT NOW() + INTERVAL '24 hours',
                    -- Outcome (populated after 7d/14d measurement)
                    outcome_snapshot_id       BIGINT       REFERENCES outcome_tracking.decision_snapshots(id) ON DELETE SET NULL,
                    outcome_velocity_lift_pct NUMERIC(8,2),
                    outcome_revenue_delta_usd NUMERIC(12,2),
                    -- Modification tracking
                    modification_count        INTEGER      NOT NULL DEFAULT 0,
                    last_modification         TEXT,
                    -- Dedup
                    UNIQUE (recommendation_id)
                )
                """
            )
            await cur.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_roadmaps_tenant_stage
                    ON whatsapp.recommendation_roadmaps (tenant_id, current_stage, created_at DESC)
                """
            )
            await cur.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_roadmaps_followup
                    ON whatsapp.recommendation_roadmaps (next_followup_at)
                    WHERE current_stage NOT IN ('completed','expired','blocked')
                """
            )
            await cur.execute(
                """
                CREATE TABLE IF NOT EXISTS whatsapp.roadmap_audit_log (
                    id          BIGSERIAL    PRIMARY KEY,
                    roadmap_id  BIGINT       NOT NULL REFERENCES whatsapp.recommendation_roadmaps(id) ON DELETE CASCADE,
                    action      TEXT         NOT NULL,
                    actor       TEXT         NOT NULL CHECK (actor IN ('retailer','system','ai')),
                    from_stage  TEXT,
                    to_stage    TEXT,
                    details     JSONB,
                    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
                )
                """
            )
            await cur.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_roadmap_audit_roadmap
                    ON whatsapp.roadmap_audit_log (roadmap_id, created_at)
                """
            )
        await conn.commit()
    finally:
        await conn.close()


# ── Roadmap lifecycle ──────────────────────────────────────────────────────────

async def create_roadmap(
    db_url: str,
    tenant_id: UUID,
    recommendation_id: str,
    sku_id: str,
    product_name: str,
    decision_type: str,
    confidence_pct: float,
    suggested_discount_pct: float | None,
    context: dict[str, str] | None = None,
) -> int:
    """
    Create a new roadmap for a recommendation.
    Idempotent — returns existing id if the recommendation_id already has a roadmap.
    Returns the roadmap id.
    """
    conf = round(confidence_pct * 100, 1) if confidence_pct and confidence_pct <= 1.0 else (confidence_pct or 0)
    ctx = context or {}

    conn = await psycopg.AsyncConnection.connect(db_url, row_factory=dict_row)
    try:
        async with conn.cursor() as cur:
            await cur.execute(
                """
                INSERT INTO whatsapp.recommendation_roadmaps
                    (tenant_id, recommendation_id, sku_id, product_name, decision_type,
                     confidence_pct, suggested_discount_pct,
                     context_summary, reasoning, expected_impact,
                     risks, alternatives, next_best_step)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                ON CONFLICT (recommendation_id) DO NOTHING
                RETURNING id
                """,
                (
                    str(tenant_id), recommendation_id, sku_id, product_name,
                    decision_type.upper(), conf, suggested_discount_pct,
                    ctx.get("context_summary"), ctx.get("reasoning"),
                    ctx.get("expected_impact"), ctx.get("risks"),
                    ctx.get("alternatives"), ctx.get("next_best_step"),
                ),
            )
            row = await cur.fetchone()
        await conn.commit()

        if row:
            roadmap_id = int(row["id"])
            await _append_audit(db_url, roadmap_id, "roadmap_created", "system",
                                to_stage="recommendation_ready")
            return roadmap_id

        # Already existed — fetch
        async with conn.cursor() as cur:
            await cur.execute(
                "SELECT id FROM whatsapp.recommendation_roadmaps WHERE recommendation_id = %s",
                (recommendation_id,),
            )
            existing = await cur.fetchone()
        return int(existing["id"]) if existing else -1
    finally:
        await conn.close()


async def advance_stage(
    db_url: str,
    roadmap_id: int,
    new_stage: str,
    actor: str = "system",
    notes: str | None = None,
    extra_updates: dict[str, Any] | None = None,
) -> None:
    """Advance a roadmap to a new stage and write an audit entry."""
    conn = await psycopg.AsyncConnection.connect(db_url, row_factory=dict_row)
    try:
        async with conn.cursor() as cur:
            await cur.execute(
                "SELECT current_stage FROM whatsapp.recommendation_roadmaps WHERE id = %s",
                (roadmap_id,),
            )
            row = await cur.fetchone()
        if not row:
            return
        old_stage = row["current_stage"]

        set_parts = ["current_stage = %s"]
        values: list[Any] = [new_stage]

        ts_map = {
            "approved": "approved_at",
            "executing": "executed_at",
            "completed": "completed_at",
        }
        if new_stage in ts_map:
            set_parts.append(f"{ts_map[new_stage]} = NOW()")

        if extra_updates:
            for k, v in extra_updates.items():
                set_parts.append(f"{k} = %s")
                values.append(v)

        values.append(roadmap_id)
        async with conn.cursor() as cur:
            await cur.execute(
                f"UPDATE whatsapp.recommendation_roadmaps SET {', '.join(set_parts)} WHERE id = %s",
                values,
            )
        await conn.commit()
    finally:
        await conn.close()

    await _append_audit(
        db_url, roadmap_id, f"stage → {new_stage}", actor,
        from_stage=old_stage, to_stage=new_stage,
        details={"notes": notes} if notes else None,
    )


async def mark_modification(
    db_url: str,
    roadmap_id: int,
    modification_text: str,
) -> None:
    """Record a modification and advance to 'modified' stage."""
    conn = await psycopg.AsyncConnection.connect(db_url, row_factory=dict_row)
    try:
        async with conn.cursor() as cur:
            await cur.execute(
                """
                UPDATE whatsapp.recommendation_roadmaps
                SET current_stage = 'modified',
                    modification_count = modification_count + 1,
                    last_modification = %s
                WHERE id = %s
                """,
                (modification_text, roadmap_id),
            )
        await conn.commit()
    finally:
        await conn.close()
    await _append_audit(db_url, roadmap_id, "modified", "retailer",
                        from_stage="awaiting_approval", to_stage="modified",
                        details={"modification": modification_text})


async def close_with_outcome(
    db_url: str,
    recommendation_id: str,
    snapshot_id: int,
    velocity_lift_pct: float | None,
    revenue_delta_usd: float | None,
) -> None:
    """Mark a roadmap as completed once outcome measurements are available."""
    conn = await psycopg.AsyncConnection.connect(db_url, row_factory=dict_row)
    try:
        async with conn.cursor() as cur:
            await cur.execute(
                """
                UPDATE whatsapp.recommendation_roadmaps
                SET current_stage = 'completed',
                    completed_at = NOW(),
                    outcome_snapshot_id = %s,
                    outcome_velocity_lift_pct = %s,
                    outcome_revenue_delta_usd = %s
                WHERE recommendation_id = %s
                  AND current_stage NOT IN ('completed','expired')
                RETURNING id
                """,
                (snapshot_id, velocity_lift_pct, revenue_delta_usd, recommendation_id),
            )
            row = await cur.fetchone()
        await conn.commit()
        if row:
            await _append_audit(
                db_url, int(row["id"]), "outcome_recorded", "system",
                to_stage="completed",
                details={
                    "snapshot_id": snapshot_id,
                    "velocity_lift_pct": velocity_lift_pct,
                    "revenue_delta_usd": revenue_delta_usd,
                },
            )
    finally:
        await conn.close()


async def get_roadmap_id_for_recommendation(db_url: str, recommendation_id: str) -> int | None:
    """Look up the roadmap id for a given recommendation_id."""
    conn = await psycopg.AsyncConnection.connect(db_url, row_factory=dict_row)
    try:
        async with conn.cursor() as cur:
            await cur.execute(
                "SELECT id FROM whatsapp.recommendation_roadmaps WHERE recommendation_id = %s",
                (recommendation_id,),
            )
            row = await cur.fetchone()
        return int(row["id"]) if row else None
    finally:
        await conn.close()


# ── Query functions (used by agent tools) ─────────────────────────────────────

async def get_roadmap_summary(db_url: str, tenant_id: UUID) -> dict[str, Any]:
    """Management-level view of all roadmaps for this tenant (last 30 days)."""
    conn = await psycopg.AsyncConnection.connect(db_url, row_factory=dict_row)
    try:
        async with conn.cursor() as cur:
            await cur.execute(
                """
                SELECT
                    id, sku_id, product_name, decision_type, current_stage,
                    confidence_pct, suggested_discount_pct,
                    reasoning, expected_impact, next_best_step,
                    modification_count, last_modification,
                    approved_at, executed_at, completed_at,
                    outcome_velocity_lift_pct, outcome_revenue_delta_usd,
                    created_at, expires_at
                FROM whatsapp.recommendation_roadmaps
                WHERE tenant_id = %s
                  AND created_at > NOW() - INTERVAL '30 days'
                ORDER BY
                    CASE current_stage
                        WHEN 'awaiting_approval'    THEN 1
                        WHEN 'blocked'              THEN 2
                        WHEN 'modified'             THEN 3
                        WHEN 'recommendation_ready' THEN 4
                        WHEN 'approved'             THEN 5
                        WHEN 'executing'            THEN 6
                        WHEN 'monitoring'           THEN 7
                        WHEN 'reviewing'            THEN 8
                        WHEN 'completed'            THEN 9
                        ELSE 10
                    END,
                    created_at DESC
                """,
                (str(tenant_id),),
            )
            rows = await cur.fetchall()
    finally:
        await conn.close()

    now = datetime.now(tz=timezone.utc)

    def _age_hours(ts: Any) -> float:
        if ts is None:
            return 0.0
        if ts.tzinfo is None:
            ts = ts.replace(tzinfo=timezone.utc)
        return round((now - ts).total_seconds() / 3600, 1)

    items = []
    by_stage: dict[str, list] = {}
    for r in rows:
        stage = r["current_stage"]
        item = {
            "roadmap_id": r["id"],
            "sku_id": r["sku_id"],
            "product_name": r["product_name"],
            "decision_type": r["decision_type"],
            "stage": STAGE_LABELS.get(stage, stage),
            "stage_key": stage,
            "confidence_pct": float(r["confidence_pct"] or 0),
            "suggested_discount_pct": float(r["suggested_discount_pct"] or 0),
            "reasoning": r["reasoning"] or "",
            "expected_impact": r["expected_impact"] or "",
            "next_best_step": r["next_best_step"] or "",
            "modification_count": r["modification_count"],
            "last_modification": r["last_modification"],
            "approved_at": r["approved_at"].isoformat() if r["approved_at"] else None,
            "outcome_velocity_lift_pct": float(r["outcome_velocity_lift_pct"]) if r["outcome_velocity_lift_pct"] else None,
            "outcome_revenue_delta_usd": float(r["outcome_revenue_delta_usd"]) if r["outcome_revenue_delta_usd"] else None,
            "age_hours": _age_hours(r["created_at"]),
        }
        items.append(item)
        by_stage.setdefault(stage, []).append(item)

    needs_attention = [i for i in items if i["stage_key"] in ("awaiting_approval", "blocked", "modified")]

    return {
        "total": len(items),
        "stage_counts": {s: len(v) for s, v in by_stage.items()},
        "by_stage": by_stage,
        "needs_attention": needs_attention,
        "needs_attention_count": len(needs_attention),
    }


async def get_recommendation_detail(db_url: str, roadmap_id: int) -> dict[str, Any]:
    """Full detail for a single roadmap including audit trail."""
    conn = await psycopg.AsyncConnection.connect(db_url, row_factory=dict_row)
    try:
        async with conn.cursor() as cur:
            await cur.execute(
                "SELECT * FROM whatsapp.recommendation_roadmaps WHERE id = %s",
                (roadmap_id,),
            )
            roadmap = await cur.fetchone()
            if not roadmap:
                return {"error": f"Roadmap {roadmap_id} not found"}
            await cur.execute(
                """
                SELECT action, actor, from_stage, to_stage, details, created_at
                FROM whatsapp.roadmap_audit_log
                WHERE roadmap_id = %s
                ORDER BY created_at
                """,
                (roadmap_id,),
            )
            audit = await cur.fetchall()
    finally:
        await conn.close()

    return {
        "roadmap": {k: (v.isoformat() if isinstance(v, datetime) else v) for k, v in dict(roadmap).items()},
        "stage_label": STAGE_LABELS.get(roadmap["current_stage"], roadmap["current_stage"]),
        "audit_trail": [
            {**{k: (v.isoformat() if isinstance(v, datetime) else v) for k, v in dict(a).items()}}
            for a in audit
        ],
    }


async def get_next_actions(db_url: str, tenant_id: UUID) -> dict[str, Any]:
    """Prioritised action list for management: what needs attention right now."""
    conn = await psycopg.AsyncConnection.connect(db_url, row_factory=dict_row)
    try:
        async with conn.cursor() as cur:
            # Pending approvals
            await cur.execute(
                """
                SELECT sku_id, product_name, decision_type, confidence_pct,
                       suggested_discount_pct, reasoning, expected_impact,
                       ROUND(EXTRACT(EPOCH FROM (NOW() - created_at))/3600, 1) AS hours_waiting
                FROM whatsapp.recommendation_roadmaps
                WHERE tenant_id = %s AND current_stage = 'awaiting_approval'
                  AND (expires_at IS NULL OR expires_at > NOW())
                ORDER BY confidence_pct DESC NULLS LAST
                """,
                (str(tenant_id),),
            )
            pending = [dict(r) for r in await cur.fetchall()]

            # Modified — waiting for re-approval
            await cur.execute(
                """
                SELECT sku_id, product_name, decision_type,
                       modification_count, last_modification, confidence_pct
                FROM whatsapp.recommendation_roadmaps
                WHERE tenant_id = %s AND current_stage = 'modified'
                ORDER BY created_at DESC
                """,
                (str(tenant_id),),
            )
            modified = [dict(r) for r in await cur.fetchall()]

            # Blocked
            await cur.execute(
                """
                SELECT sku_id, product_name, decision_type, last_modification
                FROM whatsapp.recommendation_roadmaps
                WHERE tenant_id = %s AND current_stage = 'blocked'
                ORDER BY created_at DESC
                """,
                (str(tenant_id),),
            )
            blocked = [dict(r) for r in await cur.fetchall()]

            # Overdue: approved >7d but still in monitoring
            await cur.execute(
                """
                SELECT sku_id, product_name, decision_type,
                       ROUND(EXTRACT(EPOCH FROM (NOW() - approved_at))/86400, 1) AS days_since_approval
                FROM whatsapp.recommendation_roadmaps
                WHERE tenant_id = %s
                  AND current_stage IN ('approved','executing','monitoring')
                  AND approved_at < NOW() - INTERVAL '7 days'
                ORDER BY approved_at
                """,
                (str(tenant_id),),
            )
            overdue = [dict(r) for r in await cur.fetchall()]

            # Recently completed with results
            await cur.execute(
                """
                SELECT sku_id, product_name, decision_type,
                       outcome_velocity_lift_pct, outcome_revenue_delta_usd,
                       completed_at
                FROM whatsapp.recommendation_roadmaps
                WHERE tenant_id = %s AND current_stage = 'completed'
                  AND completed_at > NOW() - INTERVAL '14 days'
                ORDER BY completed_at DESC
                LIMIT 3
                """,
                (str(tenant_id),),
            )
            completed = [dict(r) for r in await cur.fetchall()]
    finally:
        await conn.close()

    if pending:
        priority = f"You have {len(pending)} recommendation(s) waiting for your approval."
    elif modified:
        priority = f"{len(modified)} modified recommendation(s) need re-approval."
    elif overdue:
        priority = f"{len(overdue)} approved action(s) are overdue for their performance review."
    elif blocked:
        priority = f"{len(blocked)} item(s) are blocked and need attention."
    else:
        priority = "No urgent actions pending — pipeline is clear."

    return {
        "priority_action": priority,
        "pending_approvals": pending,
        "modified_pending_reapproval": modified,
        "blocked_items": blocked,
        "overdue_review": overdue,
        "recently_completed": [
            {**r, "completed_at": r["completed_at"].isoformat() if r.get("completed_at") else None}
            for r in completed
        ],
    }


# ── Rich context generation ────────────────────────────────────────────────────

async def generate_rich_context(
    anthropic_api_key: str,
    product_name: str,
    decision_type: str,
    confidence_pct: float,
    suggested_discount_pct: float | None,
    explanation: str,
    retail_price: float,
    cost_price: float,
) -> dict[str, str]:
    """
    Use Claude Haiku to generate structured recommendation context:
    reasoning, expected impact, risks, alternatives, next best step.
    Falls back to template values if the API call fails.
    """
    import anthropic as _anthropic

    discount_line = f"{int(suggested_discount_pct)}% discount" if suggested_discount_pct else "pricing action"
    new_price = retail_price * (1 - (suggested_discount_pct or 0) / 100)
    margin_after = ((new_price - cost_price) / new_price * 100) if new_price > 0 else 0

    prompt = f"""You are a retail business analyst for StylePulse, a sportswear retailer in Lebanon.
Generate a structured recommendation context for the retailer to review via WhatsApp.

Product: {product_name}
Decision: {decision_type} — {discount_line}
AI confidence: {confidence_pct:.0f}%
Primary signal: {explanation}
Retail price: ${retail_price:.2f}  |  New price after discount: ${new_price:.2f}
Margin after action: {margin_after:.1f}%

Return ONLY a JSON object with these exact keys (no markdown, no explanation):
- context_summary: 1-2 sentences — which data signals triggered this recommendation
- reasoning: 2-3 sentences — WHY this action makes sense right now
- expected_impact: 1-2 sentences — expected outcome (units sold, revenue, margin)
- risks: 1 sentence — the main risk of taking this action
- alternatives: 1 sentence — what else could be done instead
- next_best_step: 1 short sentence — the single most important thing to do next"""

    try:
        client = _anthropic.AsyncAnthropic(api_key=anthropic_api_key)
        response = await client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=600,
            messages=[{"role": "user", "content": prompt}],
        )
        text = (response.content[0].text if response.content else "").strip()
        if text.startswith("```"):
            text = text.split("```", 2)[1]
            if text.startswith("json"):
                text = text[4:]
            text = text.rsplit("```", 1)[0].strip()
        return json.loads(text)
    except Exception as exc:
        logger.warning("Rich context generation failed for %s: %s", product_name, exc)
        return {
            "context_summary": f"Inventory and pricing signals indicate action needed on {product_name}.",
            "reasoning": explanation or "AI confidence threshold met based on current stock and velocity data.",
            "expected_impact": f"Expected revenue improvement from applying {discount_line}.",
            "risks": "Margin compression if discount is deeper than needed — monitor closely.",
            "alternatives": "Hold price for one more week and monitor sales velocity.",
            "next_best_step": f"Review and approve the {decision_type.lower()} recommendation.",
        }


# ── Follow-up poller ───────────────────────────────────────────────────────────

async def roadmap_followup_loop(
    db_url: str,
    retailer_phone: str,
    tenant_id: UUID,
    wa_client: Any,
    interval_seconds: int = 3600,
) -> None:
    """
    Background task: every hour, check for roadmaps that need a follow-up nudge.
    Sends a WhatsApp reminder if a recommendation has been waiting for approval
    for more than 4 hours without a response.
    """
    import asyncio
    while True:
        await asyncio.sleep(interval_seconds)
        try:
            conn = await psycopg.AsyncConnection.connect(db_url, row_factory=dict_row)
            try:
                async with conn.cursor() as cur:
                    await cur.execute(
                        """
                        SELECT id, product_name, decision_type, confidence_pct,
                               suggested_discount_pct, reasoning,
                               ROUND(EXTRACT(EPOCH FROM (NOW() - created_at))/3600, 0) AS hours_waiting
                        FROM whatsapp.recommendation_roadmaps
                        WHERE tenant_id = %s
                          AND current_stage IN ('awaiting_approval', 'modified')
                          AND (next_followup_at IS NULL OR next_followup_at <= NOW())
                          AND (expires_at IS NULL OR expires_at > NOW())
                        ORDER BY created_at
                        LIMIT 3
                        """,
                        (str(tenant_id),),
                    )
                    due = await cur.fetchall()
            finally:
                await conn.close()

            for row in due:
                hours = int(row["hours_waiting"] or 0)
                discount = int(row["suggested_discount_pct"] or 0)
                action = "modified and awaiting re-approval" if "modified" in str(row) else "waiting for your approval"
                msg = (
                    f"⏰ *Reminder — Action Needed*\n\n"
                    f"*{row['decision_type']}: {row['product_name']}*\n"
                    f"Discount: *{discount}%* off · Confidence: *{int(row['confidence_pct'] or 0)}%*\n"
                    f"Reason: {row['reasoning'] or 'AI confidence threshold met'}\n\n"
                    f"This recommendation has been {action} for *{hours}h*.\n\n"
                    f"Reply *APPROVE*, *MODIFY [instruction]*, or *REJECT*.\n"
                    f"_(Or ask me: 'What should we do about {row['product_name']}?')_"
                )
                try:
                    await wa_client.send_text_message(retailer_phone, msg)
                    # Push next follow-up 4 hours out
                    conn2 = await psycopg.AsyncConnection.connect(db_url)
                    try:
                        async with conn2.cursor() as cur:
                            await cur.execute(
                                """
                                UPDATE whatsapp.recommendation_roadmaps
                                SET last_followup_at = NOW(),
                                    next_followup_at = NOW() + INTERVAL '4 hours'
                                WHERE id = %s
                                """,
                                (row["id"],),
                            )
                        await conn2.commit()
                    finally:
                        await conn2.close()
                    await _append_audit(db_url, int(row["id"]), "followup_sent", "system")
                    logger.info("Follow-up reminder sent for roadmap %s (%s)", row["id"], row["product_name"])
                except Exception as exc:
                    logger.warning("Follow-up send failed for roadmap %s: %s", row["id"], exc)

        except Exception as exc:
            logger.error("Roadmap follow-up loop error: %s", exc, exc_info=True)


# ── Audit helper ───────────────────────────────────────────────────────────────

async def _append_audit(
    db_url: str,
    roadmap_id: int,
    action: str,
    actor: str,
    from_stage: str | None = None,
    to_stage: str | None = None,
    details: dict | None = None,
) -> None:
    conn = await psycopg.AsyncConnection.connect(db_url)
    try:
        async with conn.cursor() as cur:
            await cur.execute(
                """
                INSERT INTO whatsapp.roadmap_audit_log
                    (roadmap_id, action, actor, from_stage, to_stage, details)
                VALUES (%s, %s, %s, %s, %s, %s)
                """,
                (
                    roadmap_id, action, actor, from_stage, to_stage,
                    json.dumps(details) if details else None,
                ),
            )
        await conn.commit()
    except Exception as exc:
        logger.debug("Audit log write failed: %s", exc)
    finally:
        await conn.close()
