import { useEffect, useMemo, useState } from 'react';
import { Bell, Building2, ListChecks, Store } from 'lucide-react';
import { toast } from 'sonner';
import { Section } from '@/components/shared/Section';
import { fetchAdminCompetitorRequests, fetchAdminNotifications, fetchAdminTenants } from '@/lib/adapter';
import { fmtNum, relativeTime } from '@/lib/format';
import type { AdminTenant, AppNotification, CompetitorRequest } from '@/types/domain';

export default function AdminDashboard() {
  const [tenants, setTenants] = useState<AdminTenant[]>([]);
  const [requests, setRequests] = useState<CompetitorRequest[]>([]);
  const [notifications, setNotifications] = useState<AppNotification[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    Promise.all([
      fetchAdminTenants(),
      fetchAdminCompetitorRequests(),
      fetchAdminNotifications(),
    ])
      .then(([nextTenants, nextRequests, nextNotifications]) => {
        setTenants(nextTenants);
        setRequests(nextRequests);
        setNotifications(nextNotifications);
      })
      .catch((error) => toast.error(error?.message || 'Could not load admin dashboard'))
      .finally(() => setLoading(false));
  }, []);

  const pendingRequests = useMemo(() => requests.filter((item) => item.status === 'pending'), [requests]);
  const unreadNotifications = useMemo(() => notifications.filter((item) => item.status === 'unread'), [notifications]);
  const totalSkus = tenants.reduce((sum, tenant) => sum + Number(tenant.sku_count || 0), 0);

  return (
    <>
      <AdminHeader title="Admin Dashboard" subtitle="Global control center for shops, requests, and notifications" />
      <main className="px-6 lg:px-8 py-6 space-y-6 animate-fade-in">
        <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4">
          <Metric icon={Store} label="Shops" value={fmtNum(tenants.length)} />
          <Metric icon={Building2} label="Total Shop SKUs" value={fmtNum(totalSkus)} />
          <Metric icon={ListChecks} label="Pending Competitor Requests" value={fmtNum(pendingRequests.length)} />
          <Metric icon={Bell} label="Unread Notifications" value={fmtNum(unreadNotifications.length)} />
        </div>

        <div className="grid xl:grid-cols-2 gap-6">
          <Section title="Latest Notifications" subtitle="Admin inbox generated by shop actions">
            {loading ? (
              <Empty>Loading notifications...</Empty>
            ) : notifications.length === 0 ? (
              <Empty>No notifications yet.</Empty>
            ) : (
              <div className="space-y-3">
                {notifications.slice(0, 6).map((item) => (
                  <div key={item.id} className="rounded-md border border-border px-3 py-2">
                    <div className="flex items-center justify-between gap-3">
                      <div className="text-sm font-semibold">{item.title}</div>
                      <Status value={item.status} />
                    </div>
                    <div className="text-xs text-muted-foreground mt-1">{item.message}</div>
                    <div className="text-[11px] text-muted-foreground mt-2">{relativeTime(item.created_at)}</div>
                  </div>
                ))}
              </div>
            )}
          </Section>

          <Section title="Pending Competitor Requests" subtitle="New competitors requested by shops">
            {loading ? (
              <Empty>Loading requests...</Empty>
            ) : pendingRequests.length === 0 ? (
              <Empty>No pending competitor requests.</Empty>
            ) : (
              <div className="space-y-3">
                {pendingRequests.slice(0, 6).map((item) => (
                  <div key={item.id} className="rounded-md border border-border px-3 py-2">
                    <div className="flex items-center justify-between gap-3">
                      <div className="text-sm font-semibold">{item.competitor_name}</div>
                      <Status value={item.status} />
                    </div>
                    <div className="text-xs text-muted-foreground mt-1">
                      {item.shop_name || 'Shop'} {item.requested_by_email ? `- ${item.requested_by_email}` : ''}
                    </div>
                    <div className="text-[11px] text-muted-foreground mt-2">{relativeTime(item.created_at)}</div>
                  </div>
                ))}
              </div>
            )}
          </Section>
        </div>
      </main>
    </>
  );
}

export function AdminHeader({ title, subtitle }: { title: string; subtitle?: string }) {
  return (
    <header className="sticky top-0 z-40 backdrop-blur-md bg-background/85 border-b border-border">
      <div className="flex items-center px-6 lg:px-8 h-16">
        <div className="min-w-0">
          <h1 className="font-display text-[19px] font-semibold tracking-tight truncate">{title}</h1>
          {subtitle && <p className="text-[13px] text-muted-foreground truncate mt-0.5">{subtitle}</p>}
        </div>
      </div>
    </header>
  );
}

function Metric({ icon: Icon, label, value }: { icon: any; label: string; value: string }) {
  return (
    <div className="rounded-xl border border-border bg-card p-5 shadow-sm-soft">
      <div className="flex items-center justify-between">
        <div className="text-[12px] uppercase tracking-wider text-muted-foreground">{label}</div>
        <Icon className="h-4 w-4 text-primary" />
      </div>
      <div className="text-data text-[28px] mt-3">{value}</div>
    </div>
  );
}

export function Status({ value }: { value: string }) {
  return (
    <span className="rounded-full bg-muted px-2 py-0.5 text-[10px] font-mono uppercase tracking-wider text-muted-foreground">
      {value}
    </span>
  );
}

export function Empty({ children }: { children: React.ReactNode }) {
  return <div className="text-sm text-muted-foreground py-8 text-center">{children}</div>;
}
