import { useEffect, useMemo, useState } from 'react';
import { Bell, Building2, ListChecks, ShieldCheck, Store } from 'lucide-react';
import { toast } from 'sonner';
import { Section } from '@/components/shared/Section';
import { fetchAdminCompetitorRequests, fetchAdminNotifications, fetchAdminTenants } from '@/lib/adapter';
import { fmtNum, relativeTime } from '@/lib/format';
import type { AdminTenant, AppNotification, CompetitorRequest } from '@/types/domain';

export default function AdminDashboard() {
  const [tenants, setTenants] = useState<AdminTenant[]>([]);
  const [requests, setRequests] = useState<CompetitorRequest[]>([]);
  const [notifications, setNotifications] = useState<AppNotification[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    Promise.all([
      fetchAdminTenants(),
      fetchAdminCompetitorRequests(),
      fetchAdminNotifications(),
    ])
      .then(([nextTenants, nextRequests, nextNotifications]) => {
        setTenants(nextTenants);
        setRequests(nextRequests);
        setNotifications(nextNotifications);
      })
      .catch((error) => toast.error(error?.message || 'Could not load admin dashboard'))
      .finally(() => setLoading(false));
  }, []);

  const pendingRequests = useMemo(() => requests.filter((item) => item.status === 'pending'), [requests]);
  const unreadNotifications = useMemo(() => notifications.filter((item) => item.status === 'unread'), [notifications]);
  const totalSkus = tenants.reduce((sum, tenant) => sum + Number(tenant.sku_count || 0), 0);

  return (
    <>
      <AdminHeader title="Admin Dashboard" subtitle="Global control center for shops, requests, and notifications" />
      <main className="relative px-6 lg:px-8 py-6 space-y-6 animate-fade-in">
        <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(780px_420px_at_12%_0%,hsl(28_96%_56%/.12),transparent),radial-gradient(720px_380px_at_100%_22%,hsl(152_60%_48%/.10),transparent),radial-gradient(620px_360px_at_84%_100%,hsl(0_84%_60%/.08),transparent)]" />
        <section className="relative overflow-hidden rounded-2xl border border-primary/25 bg-gradient-to-br from-primary/25 via-decision-markdown/10 to-decision-promote/20 p-6 shadow-lg-soft">
          <div className="absolute inset-0 bg-[radial-gradient(740px_300px_at_15%_20%,hsl(28_96%_56%/.30),transparent),radial-gradient(520px_300px_at_94%_20%,hsl(152_60%_48%/.22),transparent),radial-gradient(420px_260px_at_58%_100%,hsl(0_84%_60%/.12),transparent)]" />
          <div className="relative flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
            <div>
              <div className="inline-flex items-center gap-2 rounded-full border border-primary/25 bg-primary/10 px-3 py-1 text-[11px] font-mono uppercase tracking-[0.16em] text-primary-glow">
                <ShieldCheck className="h-3.5 w-3.5" />
                Admin workspace
              </div>
              <h2 className="mt-4 font-display text-3xl font-bold tracking-tight">
                Shops, requests, and alerts in one place.
              </h2>
              <p className="mt-2 max-w-2xl text-sm text-muted-foreground">
                Monitor the live business network and respond to shop requests quickly.
              </p>
            </div>
            <div className="rounded-xl border border-primary/25 bg-background/35 p-4 text-right backdrop-blur-sm shadow-glow-sm">
              <div className="text-[11px] uppercase tracking-wider text-muted-foreground">Unread</div>
              <div className="text-data text-4xl text-primary-glow">{unreadNotifications.length}</div>
            </div>
          </div>
        </section>

        <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4">
          <Metric icon={Store} label="Shops" value={fmtNum(tenants.length)} tone="warm" />
          <Metric icon={Building2} label="Total Shop SKUs" value={fmtNum(totalSkus)} tone="green" />
          <Metric icon={ListChecks} label="Pending Competitor Requests" value={fmtNum(pendingRequests.length)} tone="amber" />
          <Metric icon={Bell} label="Unread Notifications" value={fmtNum(unreadNotifications.length)} tone="red" />
        </div>

        <div className="grid xl:grid-cols-2 gap-6">
          <Section
            title="Latest Notifications"
            subtitle="Admin inbox generated by shop actions"
            className="border-primary/20 bg-gradient-to-br from-primary/10 via-card to-decision-promote/5"
          >
            {loading ? (
              <Empty>Loading notifications...</Empty>
            ) : notifications.length === 0 ? (
              <Empty>No notifications yet.</Empty>
            ) : (
              <div className="space-y-3">
                {notifications.slice(0, 6).map((item) => (
                  <div key={item.id} className="rounded-lg border border-primary/15 bg-gradient-to-r from-primary/10 to-background/35 px-3 py-2 shadow-sm-soft">
                    <div className="flex items-center justify-between gap-3">
                      <div className="text-sm font-semibold">{item.title}</div>
                      <Status value={item.status} />
                    </div>
                    <div className="text-xs text-muted-foreground mt-1">{item.message}</div>
                    <div className="text-[11px] text-muted-foreground mt-2">{relativeTime(item.created_at)}</div>
                  </div>
                ))}
              </div>
            )}
          </Section>

          <Section
            title="Pending Competitor Requests"
            subtitle="New competitors requested by shops"
            className="border-decision-markdown/20 bg-gradient-to-br from-decision-markdown/10 via-card to-decision-clear/5"
          >
            {loading ? (
              <Empty>Loading requests...</Empty>
            ) : pendingRequests.length === 0 ? (
              <Empty>No pending competitor requests.</Empty>
            ) : (
              <div className="space-y-3">
                {pendingRequests.slice(0, 6).map((item) => (
                  <div key={item.id} className="rounded-lg border border-decision-markdown/20 bg-gradient-to-r from-decision-markdown/10 to-background/35 px-3 py-2 shadow-sm-soft">
                    <div className="flex items-center justify-between gap-3">
                      <div className="text-sm font-semibold">{item.competitor_name}</div>
                      <Status value={item.status} />
                    </div>
                    <div className="text-xs text-muted-foreground mt-1">
                      {item.shop_name || 'Shop'} {item.requested_by_email ? `- ${item.requested_by_email}` : ''}
                    </div>
                    <div className="text-[11px] text-muted-foreground mt-2">{relativeTime(item.created_at)}</div>
                  </div>
                ))}
              </div>
            )}
          </Section>
        </div>
      </main>
    </>
  );
}

export function AdminHeader({ title, subtitle }: { title: string; subtitle?: string }) {
  return (
    <header className="sticky top-0 z-40 border-b border-primary/20 bg-gradient-to-r from-background/95 via-primary/10 to-decision-promote/10 backdrop-blur-md">
      <div className="flex items-center px-6 lg:px-8 h-16">
        <div className="min-w-0">
          <h1 className="font-display text-[19px] font-semibold tracking-tight truncate text-gradient-warm">{title}</h1>
          {subtitle && <p className="text-[13px] text-muted-foreground truncate mt-0.5">{subtitle}</p>}
        </div>
      </div>
    </header>
  );
}

function Metric({ icon: Icon, label, value, tone }: { icon: any; label: string; value: string; tone: 'warm' | 'green' | 'amber' | 'red' }) {
  const tones = {
    warm: 'from-primary/28 via-primary/10 to-primary-glow/12 border-primary/35 text-primary',
    green: 'from-decision-promote/24 via-decision-promote/10 to-decision-promote/5 border-decision-promote/35 text-decision-promote',
    amber: 'from-decision-markdown/26 via-decision-markdown/10 to-decision-markdown/5 border-decision-markdown/35 text-decision-markdown',
    red: 'from-decision-clear/24 via-decision-clear/10 to-decision-clear/5 border-decision-clear/35 text-decision-clear',
  };
  return (
    <div className={`group relative overflow-hidden rounded-xl border bg-gradient-to-br ${tones[tone]} bg-card p-5 shadow-sm-soft transition hover:-translate-y-0.5 hover:shadow-glow-sm`}>
      <div className="absolute inset-x-0 top-0 h-1 bg-current/60" />
      <div className="flex items-center justify-between">
        <div className="text-[12px] uppercase tracking-wider text-muted-foreground">{label}</div>
        <div className="rounded-lg bg-background/45 p-2 shadow-sm-soft">
          <Icon className="h-4 w-4" />
        </div>
      </div>
      <div className="text-data text-[28px] mt-3">{value}</div>
    </div>
  );
}

export function Status({ value }: { value: string }) {
  const tone =
    value === 'unread' || value === 'pending'
      ? 'border-decision-markdown/35 bg-decision-markdown-bg text-decision-markdown'
      : value === 'resolved' || value === 'active' || value === 'approved' || value === 'onboarded'
        ? 'border-decision-promote/35 bg-decision-promote-bg text-decision-promote'
        : value === 'dismissed' || value === 'rejected' || value === 'inactive' || value === 'suspended' || value === 'archived'
          ? 'border-decision-clear/35 bg-decision-clear-bg text-decision-clear'
          : 'border-border bg-muted text-muted-foreground';
  return (
    <span className={`rounded-full border px-2 py-0.5 text-[10px] font-mono uppercase tracking-wider ${tone}`}>
      {value}
    </span>
  );
}

export function Empty({ children }: { children: React.ReactNode }) {
  return <div className="text-sm text-muted-foreground py-8 text-center">{children}</div>;
}
