"""
AI Engine — LLM-orchestrated Telegram conversation with Anthropic tool calling.

Architecture: Claude is the brain. It calls tools to fetch live business data,
decides what's relevant, and composes a natural Telegram-native reply.
The system prompt is cached via Anthropic prompt caching for cost efficiency.
"""
from __future__ import annotations

import asyncio
import json
import logging
import os
from typing import Any, Callable, Coroutine
from uuid import UUID

import anthropic
import httpx
import psycopg
from psycopg.rows import dict_row

logger = logging.getLogger("telegram_assistant.ai_engine")

MAX_TOOL_ITERATIONS = 5

SYSTEM_PROMPT = """\
You are Radar — a senior inventory and pricing analyst embedded in the owner's Telegram for StylePulse, a multi-brand sportswear retailer in Lebanon.

## WHO YOU ARE
Think of yourself as the sharpest ops manager the owner has ever hired. You know their numbers cold, you watch competitors, and you give honest, specific advice — not vague reassurances. You are not a rule engine. You look at the actual data and tell the owner what it means.

Tone: direct, warm, confident. Not robotic, not sycophantic.
Language: English by default. Match the language if the owner writes in Arabic or mixes both.
Format: *bold* with asterisks. Line breaks for lists. No # headers. No code blocks. Under 400 words unless they ask for a full report. Always use USD.

## YOUR TOOLS — LIVE DATA ONLY
All data comes from live systems:
- Inventory, stock, and sales: real-time from the store's database (AWS RDS)
- Competitor prices: scraped every 24–48h from 7 Lebanese retailers (Adidas LB, City Sport, KIX, Marka Store, Mike Sport, Shoes World, Tchooz)
- AI recommendations: generated by a machine learning model trained on inventory, pricing, and competitive data

NEVER present information without anchoring it to what the live data actually shows. Always name the source.

## HOW TO INTERPRET RECOMMENDATIONS
When you receive a recommendation (from get_pending_recommendations or get_recommendation_detail), you will see a structured `live_signals` object with the real inventory and competitive data for that SKU. This is what the model worked from.

Your job is to read that data as a senior analyst and explain to the owner:
- What the data actually shows (the numbers, not category labels)
- Why this particular moment — not next week, right now
- What the likely outcome is if they act vs if they wait
- Where the risk is and how serious it is
- What an alternative would look like

Do not mechanically map scores to labels. Look at the data and reason from it. A 73% score matters less than the fact that 3 of 5 competitors are actively discounting and the stock has been sitting for 94 days.

When a `confidence_context` field is present, use it as your starting point but form your own view from `live_signals`. The context tells you what the model was doing — your job is to explain what it means in business terms.

When `rule_override` is present, explain in plain language what business protection it triggered and why that protection exists. Don't just name the rule.

When `model_signals` are present, pick the 2–3 most meaningful ones and explain them in terms the owner understands — not feature names, but what those features mean for their cash, their margin, or their competitive position.

## HOW TO PRESENT CONFIDENCE
Never say just a number. Always connect it to what the data shows. Examples:
- "The model is 73% confident because your stock is 4 days above the healthy ceiling, 3 of 5 competitors are on sale, and your margin has enough room for a clean promotion."
- "Confidence is only 54% — the stock isn't moving unusually slowly yet, and competitor discounting is limited to 1 shop. This is a cautious signal, not a clear one."
- "Confidence is high here because a business protection fired: this item hasn't been discounted in 45 days, margin is comfortable, and a competitor just went out of stock — all three align."

If the data is mixed or the score is below 60%, tell the owner that directly. They need honest advice, not manufactured certainty.

## INVENTORY MANAGEMENT — YOUR PRIMARY ROLE
The owner uses you to compete and protect their capital. Every interaction should help them:
- Know exactly where they stand: which SKUs are healthy, which are trapped, which are at risk
- Act before it costs them: dead stock compounds, competitor out-of-stocks are time-limited opportunities
- Keep margin: losing 5 margin points to move 10 extra units is usually not worth it — do the math
- Prioritise: when multiple things need attention, rank by financial impact (value at risk)

When asked "what should I focus on today?" — call get_next_actions and get_inventory_overview in parallel, then give a ranked list with the one highest-impact action first.

## RECOMMENDATION PIPELINE
Every recommendation moves through a lifecycle:
  🔍 Discovery → 💡 Ready → ⏳ Awaiting Approval → ✅ Approved → ⚙️ Executing → 📊 Monitoring → 📋 Reviewing → 🏁 Completed

Use get_roadmap_summary for a pipeline overview.
Use get_recommendation_detail for deep analysis of a specific recommendation — it includes live_inventory_now so you can compare what the data showed when the recommendation was generated vs right now.
Use get_next_actions to surface what needs the owner's attention.

## APPROVALS
The owner won't type formal commands. Understand intent:
- "sounds good", "yalla", "do it", "go ahead" → approve_recommendation
- "no", "skip", "not now", "pass" → reject_recommendation
- "let's try 20% instead" → approve_recommendation with modified_discount_pct=20.0

Before approving, confirm product name and discount once if anything is ambiguous.

## OUTCOMES
When reviewing completed items, connect what happened to what was predicted:
- "Velocity lifted 34% vs the 20% projection — the promotion worked well."
- "Revenue delta was $1,200 — model was 12% optimistic. Worth noting for next time."

Use past outcomes to calibrate current recommendations when relevant.

## GROUND RULES
- Never invent numbers. If a tool returns nothing, say so and suggest what to do next.
- Cash runway below 2 months: flag it at the top of any financial response, without exception.
- Lebanon context: 3–8 week import lead times, ~85% cash payments, generator costs ~$220/month.
- End every reply with one concrete next action unless it's pure chitchat.

## CHITCHAT
Greetings and casual messages: reply naturally, no tool calls. Keep it short. Suggest a useful starting point if it's morning or the owner seems unsure what to ask.
"""


class AIEngine:
    def __init__(
        self,
        business_data_service: Any,
        db_url: str,
        ie3_base_url: str,
    ) -> None:
        from services.telegram_assistant.assistant_tools import TOOLS
        self._bds = business_data_service
        self._db_url = db_url
        self._ie3 = ie3_base_url.rstrip("/")
        self._tools = TOOLS
        api_key = os.environ.get("ANTHROPIC_API_KEY", "")
        self._client = anthropic.AsyncAnthropic(api_key=api_key or "not-set")
        # Built lazily in _build_dispatch to avoid capturing self before __init__ completes
        self._dispatch: dict[str, Callable[..., Coroutine[Any, Any, Any]]] | None = None

    @property
    def is_configured(self) -> bool:
        key = os.environ.get("ANTHROPIC_API_KEY", "").strip()
        return bool(key) and "xxxx" not in key.lower() and key != "not-set"

    async def chat(
        self,
        chat_id: str,
        user_text: str,
        message_history: list[dict],
        conversation_summary: str | None,
        tenant_id: UUID,
    ) -> tuple[str, list[str]]:
        messages = _build_messages(user_text, message_history, conversation_summary)
        tools_used: list[str] = []

        for _ in range(MAX_TOOL_ITERATIONS):
            response = await self._client.messages.create(
                model="claude-sonnet-4-6",
                max_tokens=1024,
                system=[
                    {
                        "type": "text",
                        "text": SYSTEM_PROMPT,
                        "cache_control": {"type": "ephemeral"},
                    }
                ],
                tools=self._tools,
                messages=messages,
            )

            if response.stop_reason == "end_turn":
                return _extract_text(response.content), tools_used

            if response.stop_reason == "tool_use":
                tool_blocks = [b for b in response.content if b.type == "tool_use"]
                tools_used.extend(b.name for b in tool_blocks)

                # Run all tool calls in this turn concurrently — common when Claude
                # asks for inventory + recommendations + financials in one shot.
                results = await asyncio.gather(
                    *[
                        self._execute_tool(b.name, dict(b.input), tenant_id, chat_id)
                        for b in tool_blocks
                    ]
                )
                tool_results = [
                    {
                        "type": "tool_result",
                        "tool_use_id": b.id,
                        "content": json.dumps(r, default=str),
                    }
                    for b, r in zip(tool_blocks, results)
                ]
                messages.append({"role": "assistant", "content": list(response.content)})
                messages.append({"role": "user", "content": tool_results})

        # Exhausted iterations — Claude was mid-reasoning; surface what it last said if possible
        last_text = _extract_text(response.content) if response.content else ""
        return (
            last_text
            or "I need a moment to gather more data — please ask again so I can give you a complete answer."
        ), tools_used

    def _get_dispatch(
        self, tenant_id: UUID, chat_id: str
    ) -> dict[str, Callable[..., Coroutine[Any, Any, Any]]]:
        """Return the tool-name → async handler mapping, built once per call context."""
        tid = str(tenant_id)

        async def _pending_recommendations(_inp: dict) -> Any:
            recs = await self._bds.get_pending_recommendations(tid)
            result = []
            for r in recs:
                sku_id_r = r["sku_id"]
                disc = float(r.get("suggested_discount_pct") or 0)
                confidence = int(r.get("confidence_pct") or 0)
                fallback = bool(r.get("fallback_used"))
                rule = r.get("rule_override_json")

                try:
                    live = await self._bds.get_live_signals_for_recommendation(tid, sku_id_r, disc)
                except Exception as live_exc:
                    logger.warning("Live signal fetch failed for %s: %s", sku_id_r, live_exc)
                    live = {}

                if fallback:
                    confidence_context = (
                        "Model confidence was below the minimum threshold — "
                        "signals are mixed and this defaulted to HOLD. "
                        "Human judgment is essential here."
                    )
                elif rule:
                    confidence_context = (
                        f"Score overridden by a hard business protection: "
                        f"{rule.get('rule_id','')} — {rule.get('reason','')}. "
                        "The ML probability is secondary here."
                    )
                else:
                    confidence_context = (
                        f"The ML model assigned {confidence}% probability to this action "
                        "based on the live inventory and competitor signals below. "
                        "Interpret the score relative to what the data actually shows — "
                        "a high score means the signals strongly converge; a lower score "
                        "means fewer signals agree and more caution is warranted."
                    )

                shap = r.get("shap_features_json") or []
                model_signals = []
                if isinstance(shap, list) and shap:
                    for s in shap[:3]:
                        model_signals.append({
                            "feature": s.get("feature_name", s.get("feature", "")),
                            "value": s.get("feature_value"),
                            "pushed_toward": s.get("direction", "").replace(
                                "increases_probability", r.get("recommendation", "")
                            ).replace(
                                "decreases_probability", "away from " + r.get("recommendation", "")
                            ),
                            "plain_english": s.get("explanation", ""),
                        })

                result.append({
                    "recommendation_id": str(r["id"]),
                    "action": r["recommendation"],
                    "confidence_pct": confidence,
                    "confidence_context": confidence_context,
                    "model_signals": model_signals,
                    "live_signals": live,
                    "rule_override": {
                        "rule_id": rule.get("rule_id", ""),
                        "reason": rule.get("reason", ""),
                        "blocked_actions": rule.get("blocked_actions", []),
                    } if rule else None,
                    "model_version": r.get("model_version") or "unknown",
                    "generated_at": str(r.get("generated_at", "")),
                })
            return result

        async def _recommendation_detail(inp: dict) -> Any:
            from services.telegram_assistant.recommendation_roadmap import get_recommendation_detail
            detail = await get_recommendation_detail(self._db_url, int(inp["roadmap_id"]))
            sku_id = detail.get("roadmap", {}).get("sku_id") if isinstance(detail.get("roadmap"), dict) else None
            if sku_id:
                try:
                    detail["live_inventory_now"] = await self._bds.get_sku_live_snapshot(tid, sku_id)
                except Exception as snap_exc:
                    logger.debug("Live snapshot fetch failed for %s: %s", sku_id, snap_exc)
            return detail

        return {
            "get_inventory_overview": lambda _: self._bds.get_inventory_overview(tid),
            "get_stockout_days": lambda _: self._bds.get_stockout_days(tid),
            "get_reorder_suggestions": lambda _: self._bds.get_reorder_suggestions(tid),
            "get_sku_velocity_trend": lambda inp: self._bds.get_sku_velocity_trend(
                tid, inp["sku_id"], inp.get("days", 30)
            ),
            "get_category_performance": lambda inp: self._bds.get_category_performance(
                tid, inp.get("days", 30)
            ),
            "get_financials": lambda _: self._bds.get_financials_snapshot(tid),
            "get_revenue_trend": lambda _: self._bds.get_revenue_trend(tid),
            "get_competitor_prices": lambda inp: self._bds.get_competitor_prices(
                tid, sku_id=inp.get("sku_id"), competitor_name=inp.get("competitor_name")
            ),
            "get_pending_recommendations": _pending_recommendations,
            "approve_recommendation": lambda inp: self._action_approve(
                inp["recommendation_id"], inp["sku_id"], inp.get("modified_discount_pct"),
                tenant_id, chat_id,
            ),
            "reject_recommendation": lambda inp: self._action_reject(
                inp["recommendation_id"], inp["sku_id"], tenant_id, chat_id,
            ),
            "get_decision_progress": lambda _: self._get_decision_progress(tenant_id),
            "get_roadmap_summary": lambda _: self._get_roadmap_summary(tenant_id),
            "get_recommendation_detail": _recommendation_detail,
            "get_next_actions": lambda _: self._get_next_actions(tenant_id),
        }

    async def _get_decision_progress(self, tenant_id: UUID) -> Any:
        from services.telegram_assistant.outcome_tracking import get_closed_loop_summary
        return await get_closed_loop_summary(self._db_url, tenant_id)

    async def _get_roadmap_summary(self, tenant_id: UUID) -> Any:
        from services.telegram_assistant.recommendation_roadmap import get_roadmap_summary
        return await get_roadmap_summary(self._db_url, tenant_id)

    async def _get_next_actions(self, tenant_id: UUID) -> Any:
        from services.telegram_assistant.recommendation_roadmap import get_next_actions
        return await get_next_actions(self._db_url, tenant_id)

    async def _execute_tool(
        self,
        name: str,
        inp: dict,
        tenant_id: UUID,
        chat_id: str,
    ) -> Any:
        dispatch = self._get_dispatch(tenant_id, chat_id)
        handler = dispatch.get(name)
        if handler is None:
            return {"error": f"Unknown tool: {name}"}
        try:
            return await handler(inp)
        except Exception as exc:
            logger.error("Tool %s failed: %s", name, exc, exc_info=True)
            return {"error": str(exc)}

    async def _action_approve(
        self,
        recommendation_id: str,
        sku_id: str,
        modified_discount_pct: float | None,
        tenant_id: UUID,
        chat_id: str,
    ) -> dict[str, Any]:
        conn = await psycopg.AsyncConnection.connect(self._db_url, row_factory=dict_row)
        rec = None
        try:
            async with conn.cursor() as cur:
                await cur.execute(
                    """
                    SELECT r.id, r.recommendation, r.confidence, r.suggested_discount_pct,
                           r.explanation, sv.sku_id, p.name AS product_name,
                           sv.cost_price_usd,
                           COALESCE(pr.amount, 0) AS retail_price_usd
                    FROM marketing.recommendations r
                    JOIN core.sku_variants sv ON sv.id = r.variant_id
                    JOIN core.products p ON p.id = sv.product_id
                    LEFT JOIN LATERAL (
                        SELECT amount FROM core.prices
                        WHERE variant_id = sv.id
                          AND price_type = 'retail'
                          AND valid_to IS NULL
                        LIMIT 1
                    ) pr ON true
                    WHERE r.id = %s AND r.tenant_id = %s
                    """,
                    (recommendation_id, str(tenant_id)),
                )
                rec = await cur.fetchone()

            async with conn.cursor() as cur:
                await cur.execute(
                    """
                    UPDATE marketing.recommendations
                    SET status = 'approved', reviewed_at = now(), reviewed_by = 'telegram'
                    WHERE id = %s
                    """,
                    (recommendation_id,),
                )
            await conn.commit()
        finally:
            await conn.close()

        if not rec:
            return {"status": "error", "message": f"Recommendation {recommendation_id} not found."}

        rec_type = rec["recommendation"]
        product_name = rec.get("product_name") or sku_id
        confidence = float(rec.get("confidence") or 0.8)
        discount_pct = (
            modified_discount_pct
            if modified_discount_pct is not None
            else float(rec.get("suggested_discount_pct") or 15)
        )
        explanation = rec.get("explanation") or "AI recommendation"

        campaign_status = "not_applicable"
        if rec_type == "PROMOTE":
            try:
                body = {
                    "sku_id": sku_id,
                    "product_name": product_name,
                    "recommendation": "PROMOTE",
                    "confidence": confidence,
                    "explanation": explanation,
                    "shap_top5": [],
                    "suggested_discount_pct": discount_pct,
                    "requires_human_approval": True,
                    "fallback_used": False,
                    "model_version": "rules_v1",
                    "processing_time_ms": 0,
                }
                async with httpx.AsyncClient(timeout=90.0) as client:
                    resp = await client.post(f"{self._ie3}/campaign/generate", json=body)
                    resp.raise_for_status()
                campaign_status = "generated"
                logger.info("IE3 campaign generated for sku=%s", sku_id)
            except Exception as exc:
                campaign_status = f"failed: {exc}"
                logger.error("IE3 campaign failed for sku=%s: %s", sku_id, exc)

        from services.telegram_assistant.outcome_tracking import record_decision_snapshot
        snapshot_id = await record_decision_snapshot(
            sku_id=sku_id,
            decision_type=rec_type,
            recommendation_id=recommendation_id,
            cost_price_usd=float(rec.get("cost_price_usd") or 0),
            tenant_id=tenant_id,
        )

        # Try to update notification outcome if a notification exists for this recommendation
        await _update_notification_outcome_if_exists(self._db_url, recommendation_id, "approved")

        # Advance roadmap: approved → executing
        from services.telegram_assistant.recommendation_roadmap import (
            get_roadmap_id_for_recommendation, advance_stage,
        )
        try:
            roadmap_id = await get_roadmap_id_for_recommendation(self._db_url, recommendation_id)
            if roadmap_id:
                await advance_stage(self._db_url, roadmap_id, "approved", actor="retailer")
                await advance_stage(self._db_url, roadmap_id, "executing", actor="system",
                                    notes="Campaign generation triggered via chat")
                if snapshot_id:
                    await advance_stage(self._db_url, roadmap_id, "monitoring", actor="system",
                                        notes=f"Outcome tracking started — snapshot #{snapshot_id}",
                                        extra_updates={"outcome_snapshot_id": snapshot_id})
        except Exception as exc:
            logger.warning("Roadmap advance on approve (agent) failed: %s", exc)

        from services.telegram_assistant.conversation_store import ConversationManager
        await ConversationManager(self._db_url).clear_flow(chat_id)

        return {
            "status": "approved",
            "sku_id": sku_id,
            "product_name": product_name,
            "recommendation_type": rec_type,
            "discount_pct": discount_pct,
            "campaign_status": campaign_status,
            "snapshot_id": snapshot_id,
        }

    async def _action_reject(
        self,
        recommendation_id: str,
        sku_id: str,
        tenant_id: UUID,
        chat_id: str,
    ) -> dict[str, Any]:
        conn = await psycopg.AsyncConnection.connect(self._db_url, row_factory=dict_row)
        try:
            async with conn.cursor() as cur:
                await cur.execute(
                    """
                    UPDATE marketing.recommendations
                    SET status = 'rejected', reviewed_at = now(), reviewed_by = 'telegram'
                    WHERE id = %s AND tenant_id = %s
                    """,
                    (recommendation_id, str(tenant_id)),
                )
            await conn.commit()
        finally:
            await conn.close()

        await _update_notification_outcome_if_exists(self._db_url, recommendation_id, "rejected")

        # Advance roadmap to 'expired'
        from services.telegram_assistant.recommendation_roadmap import (
            get_roadmap_id_for_recommendation, advance_stage,
        )
        try:
            roadmap_id = await get_roadmap_id_for_recommendation(self._db_url, recommendation_id)
            if roadmap_id:
                await advance_stage(self._db_url, roadmap_id, "expired", actor="retailer",
                                    notes="Rejected via chat")
        except Exception as exc:
            logger.warning("Roadmap advance on reject (agent) failed: %s", exc)


        from services.telegram_assistant.conversation_store import ConversationManager
        await ConversationManager(self._db_url).clear_flow(chat_id)

        return {"status": "rejected", "sku_id": sku_id}


# ── Helpers ───────────────────────────────────────────────────────────────────

async def _update_notification_outcome_if_exists(
    db_url: str, recommendation_id: str, outcome: str
) -> None:
    """Update notification outcome if a promote_notification row exists for this recommendation."""
    conn = await psycopg.AsyncConnection.connect(db_url, row_factory=dict_row)
    try:
        async with conn.cursor() as cur:
            await cur.execute(
                """
                UPDATE telegram.promote_notifications
                SET outcome = %s, outcome_at = now()
                WHERE recommendation_id = %s
                  AND outcome = 'pending'
                """,
                (outcome, recommendation_id),
            )
        await conn.commit()
    except Exception as exc:
        logger.debug("Could not update notification outcome: %s", exc)
    finally:
        await conn.close()


def _build_messages(
    user_text: str,
    history: list[dict],
    conversation_summary: str | None,
) -> list[dict]:
    messages: list[dict] = []

    if conversation_summary:
        messages.append({
            "role": "user",
            "content": f"[Earlier conversation summary]\n{conversation_summary}",
        })
        messages.append({
            "role": "assistant",
            "content": "Understood — I have context from our earlier conversation.",
        })

    for entry in history:
        role = entry.get("role", "user")
        content = entry.get("content", "")
        if role in ("user", "assistant") and content:
            messages.append({"role": role, "content": content})

    messages.append({"role": "user", "content": user_text})
    return messages


def _extract_text(content: list) -> str:
    parts = [block.text for block in content if hasattr(block, "type") and block.type == "text"]
    return "\n".join(parts).strip() or "I couldn't generate a reply — please try again."
